### ISSUE TITLE
Use the STAC UML to populate missing fields

### ISSUE THREAD

**Issue by bo-lu** [Canadian-Geospatial-Platform/stac-to-geocore#1]
Relevant links:

https://github.com/radiantearth/stac-spec/blob/master/STAC-UML.pdf
https://github.com/radiantearth/stac-api-spec/tree/master/stac-spec
https://github.com/radiantearth/stac-api-spec/blob/master/stac-spec/overview.md
https://github.com/radiantearth/stac-api-spec/tree/master/item-search
https://github.com/radiantearth/stac-api-spec/tree/master/item-search#query-parameter-table

**Comment by xinli-cai** [comment]
@bo-lu Some of the missing fields can be extracted from the collection level, and some missing fields are currently hardcoded for CCMEO data cube. Solutions for the missing fields are documented in [this spreadsheet](https://041gc-my.sharepoint.com/:x:/g/personal/xinli_cai_nrcan-rncan_gc_ca/EbHpd-7qeidNoqBIeeecUQMBwymgMuYzK3KJwUJgUObjoQ) for review. Codes will be committed to the repo for review.

**Comment by xinli-cai** [comment]
Codes are committed to the main brunch: https://github.com/Canadian-Geospatial-Platform/stac_to_geocore/commit/200c8994b01497493c4ef92f74904d43eac22230

**Comment by bo-lu** [comment]
main brunch: sounds tasty ;)
