### ISSUE TITLE
Add child-parent relations for STAC records 

### ISSUE THREAD

**Issue by xinli-cai** [Canadian-Geospatial-Platform/stac-to-geocore#3]
The collections are showing up on the metadata details page. STAC records are all at the item level on the metadata page, it would be nice to populate the collection-level information for STAC records when translating it to GeoCore format. 

Example on metadata page: an example here https://app-dev.geo.ca/result?id=085024ac-5a48-427a-a2ea-d62af73f2142&lang=en.
Related GeoCore:https://geocore-dev.metadata.geo.ca/085024ac-5a48-427a-a2ea-d62af73f2142.geojson

@bo-lu help wanted from you. I know the GeoCore parentIdentifier field can be used to identify child-parent, does it require a specific format?

**Comment by bo-lu** [comment]
I think this is complete.

**Comment by xinli-cai** [comment]
Yes, this is completed. Codes are committed to dev and are merged into the main brunch. Code related to this issue is in this commit: https://github.com/Canadian-Geospatial-Platform/stac_to_geocore/commit/082ce78747f15e7b69915a72e889e563b509bc79
