### ISSUE TITLE
Harvest the 'catalog' level and set parents of 'collection' to the 'catalog'

### ISSUE THREAD

**Issue by bo-lu** [Canadian-Geospatial-Platform/stac-to-geocore#4]

**Comment by xinli-cai** [comment]
Hey Bo, can you provide some details about this issue? For example, the[ CCMEO root API ](https://datacube.services.geo.ca/api/) is the 'catalog' level, do you mean harvesting the root api and set it as the 'parent' level of the  'collection' level? 

Currently, the root api is shown at the 'Data Sources' section of the geo.ca matadata page.

**Comment by bo-lu** [comment]
Yes, the 'parentIdentifier' for the collection should be the catalog.

**Comment by bo-lu** [comment]
From a user perspective, the navigation of the STAC is simplified. If we promote the STAC 'catalog' in the search results then users can easier discover stac collections and then stac items.

**Comment by xinli-cai** [comment]
Added harvesting and mapping to the CCMEO Data Cube root API (i.e., catalog level), details in [dev commit 666e9d0](https://github.com/Canadian-Geospatial-Platform/stac_to_geocore/commit/666e9d00e990f1983d148d921e53ed3920aebed0) . 
Here is the ['catalog' metadata page](https://app-dev.geo.ca/result?id=Franklin%20STAC%20API&lang=en) on geo.ca, the 'collections' are the child of this catalog. @bo-lu Can you review the codes and the page? Thanks!

**Comment by bo-lu** [comment]
It looks good to me!
